# Tutorial numpy

o numpy é uma biblioteca python,a qual é utilizada para realizar métodos matemáticos principalmente para algebra linear.A razão que torna o numpy tão importante para a ciência de dados é que ele é a base de construção dos modelos,um exemplo prático disso que é que o array numpy é usado para armazenamento dos dados de treinamento de um modelo de machine learning.

In [1]:
import numpy as np

Array é uma estrutura de dados que armazena uma coleção de elementos.Também pode ser chamado de matriz ou vetores.

In [2]:
lista=[4,2,6]

criando um array

In [3]:
array=np.array(lista)
array

array([4, 2, 6])

In [4]:
list=[[1,3,4],[3,4,6]]
array2=np.array(list)

In [5]:
array2

array([[1, 3, 4],
       [3, 4, 6]])

Métodos incorporados para criar arrays

Arange-Essa função faz um arranjo que retorna valores uniformemente espaçados dentro de um determinado intervalo 

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

ones e zeros-gerar matrizes com todos elemntos com zero e um,respectivamente

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Eye/indentity

Eye/identity-Gerar uma matriz indentidade

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

linspace-Retorna numeros uniformemente espaçados dentro de um intervalo

np.linspace(a,b,c) a e b formarão o intervalo c numero de elementos

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Random-criar arrays aleatorios

rand-pra criar arrays aleatorios no intervalo de 0 a 1

np.random.rand(a) a-numero de elelemntos no array

In [14]:
np.random.rand(2)

array([0.78082337, 0.35032683])

In [ ]:
randn-

In [16]:
np.random.randn(2)

array([-0.20084728, -0.21662875])

radint-Retorna valores inteiros aleatorios dentro do intervalo escolhido

np.random.randint(a,b,c) a,b-intervalo c- numero de elementos

In [17]:
np.random.randint(0,10,5)

array([2, 1, 2, 3, 8])

# identificando tributos e metodos de um array

Shape-identificar a dimensão do array

In [18]:
array2.shape

(2, 3)

reshape-redimensionar o seu array ou matriz

In [19]:
array3=array2.reshape(3,2)

In [20]:
array3

array([[1, 3],
       [4, 3],
       [4, 6]])

# indexação e seleção

No geral as formas mais simples de escolher um elemento é parecida com de listas do python

In [21]:
#escolhendo um elemento
a=np.arange(1,6)
a[4]

5

In [22]:
# escolhendo um elemento de uma matriz com mais de uma linha
array3[2][1]

6

In [23]:
# escolhendo um intervalo de valores
a[0:3]

array([1, 2, 3])

In [24]:
b=np.linspace(-5,5,10)
b

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

array booleano - Retornam apenas verdadeiro ou falso

In [25]:
b>0

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
bol_b=b>2

In [27]:
bol_b

array([False, False, False, False, False, False, False,  True,  True,
        True])

# operações aritiméticas com numpy

In [28]:
a=np.arange(0,8)
b=np.linspace(0,5,8)

In [31]:
# soma e subtração- os arrays devem ter o mesmo tamanho
a+b

array([ 0.        ,  1.71428571,  3.42857143,  5.14285714,  6.85714286,
        8.57142857, 10.28571429, 12.        ])

In [32]:
#subtração
a-b

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [33]:
# multiplicação 
a*b

array([ 0.        ,  0.71428571,  2.85714286,  6.42857143, 11.42857143,
       17.85714286, 25.71428571, 35.        ])

In [34]:
#divisão-quando se divide por zero o program retorna nan
a/b

<ipython-input-34-7c9a35aac4f2>:2: RuntimeWarning: invalid value encountered in true_divide
  a/b


array([nan, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4])

In [35]:
#potenciação
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

# operações de funções matriziais

In [36]:
#Raiz quadrada
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [37]:
#exponencial
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [38]:
#logoritimo
np.log(a)

<ipython-input-38-16ae0e235cca>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [39]:
#trigonométricas
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ])

# operações de funções matriziais

In [40]:
#transformando um array em matriz
c=np.linspace(0,9,9).reshape(3,3)

In [41]:
cm=np.mat(c)
cm

matrix([[0.   , 1.125, 2.25 ],
        [3.375, 4.5  , 5.625],
        [6.75 , 7.875, 9.   ]])

In [42]:
# transposição de matriz
np.transpose(cm)

matrix([[0.   , 3.375, 6.75 ],
        [1.125, 4.5  , 7.875],
        [2.25 , 5.625, 9.   ]])

In [43]:
# inversa
d=np.mat(np.linspace(0,5,4).reshape(2,2))

In [44]:
e=np.linalg.inv(d)
e

matrix([[-0.9,  0.3],
        [ 0.6,  0. ]])

In [46]:
from numpy import linalg

In [47]:
linalg.inv(d)

matrix([[-0.9,  0.3],
        [ 0.6,  0. ]])

In [45]:
#multiplicação de matrizes
np.dot(d,e)

matrix([[1., 0.],
        [0., 1.]])

# Exercícios 

1. Crie um array com 10 elementos usando a função arange;
2. Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape;
3. Crie duas matrizes a partir de dois arrays;
4. Crie duas matrizes e realize a multiplicação das mesmas.
